### ISSUE TITLE
Stability and planned progress of the new router

### ISSUE THREAD

**Issue by RobertjanTuit** [angular/router#194]
Hi,

Awesome work on the new router! Very excited to see 1.x a 2 path being available.

We just started a new angular project and were wondering how stable you guys consider the new router to be and how fully functional it is expected to be in what timeframe (as in days vs weeks vs months). We tried it about 4 days ago and ran into a bunch of things not working yet like: named endpoint child routes, redirects. Is there going to be a lot of immediate iteration on it or should we wait a little bit longer before depending on it?

Thanks in advance!

Cheers,
_Rj

**Comment by btford** [comment]
I'll recommend building production apps with it once it hits 1.0, which should be in a couple weeks. There will definitely be additions to the API to expose more behaviors, but I don't expect things to change radically between now and 1.0, and from 1.0 to 1.x.

It'll be a bit less battle tested than UI Router for a while, but I'll be following up regularly with updates.

If you're starting a new project, definitely consider using this project.

I'm going to close this (since it's not actionable), but feel free to follow up with other questions.

**Comment by RobertjanTuit** [comment]
Thanks Brian! With 1.0 a few weeks away, we will be test driving the new router in our new app until that happens.
