### ISSUE TITLE
Suggestion: Make this project a bigger priority for the Angular team

### ISSUE THREAD

**Issue by hannahhoward** [angular/router#234]
Hey guys,

   At ng-conf, the router was positioned as the main bridge between Angular 1 and Angular 2. That makes it a vital component for a whole whole lot people. I was surprised to see the project is not as far along as described-- there's not any way at all to use it with NG2 yet, and moreover it seems like a lot of stuff is incomplete. I discovered while implementing support for directives just how many hiccups there will be in setting this up to work well with NG 1 source code. From the outside, it seems like most of the Angular team is focused on ongoing speed improvements in NG2--- and I get that NG2 is the new shiny where you can implement a bunch of great ideas for the web of tomorrow -- but meanwhile it seems like @btford is the only one left on this project, which for the rest of the world is by far the most important thing so we can start prepping our NG1 projects for NG2. There's a line of pull requests and issues, and not a lot of engagement from whomever are the core contributors. Anyway, just trying to offer some feedback on the optics from the outside-- this isn't meant as criticism as at all -- thank you all for all that you do on Angular and I know yall are working incredibly hard.

**Comment by maku** [comment]
+1, I completely agree with this statement. From my point of view the router is an essential part to play around with ng2 (and so to be able to give feedback). Many people out there would like to know how the new router is integrated in ng2 (and to prep ng1 apps )

There is a "progress" document ( https://docs.google.com/document/d/1-DBXTHaeec6XH5qx2tKVrgrjiILy76_lSrjgJv95RJ4/edit#) where the last entry is for March 2nd !!

Core contributors are busy in many areas but not in routing (other than finding a new name for the router)
I think the (urgently waiting) community would really appreciate any progress.

**Comment by btford** [comment]
Thanks for the feedback!

Much of the work in the compiler has been to clear the way for routing in Angular 2. See b69f3043e031a4a7c08259ef5c2ec034875fd6d2, 7488456d6819b230b294971b4bed250b95373142, and 2041860a21c021efc10589533f23c8df6dc611d3 in angular/angular.

Apologies on the doc not getting updated. I partially automate those messages from my own task list system, and my script for syncing to the doc seems to have broken. I've updated the doc with what I've been up to.

There are only so many hours in the day, and the more time I spend replying to threads like this and writing docs about my progress, the less I have to actually get code out there. I realize it's frustrating to not have great insights to what's happening always, but please understand that I'm doing my best. Striking the right balance is a bit tricky.

I'm going to close this since it's not totally actionable, but feel free to keep the discussion going.

**Comment by weolopez** [comment]
from the progress [doc]
(https://docs.google.com/document/d/1-DBXTHaeec6XH5qx2tKVrgrjiILy76_lSrjgJv95RJ4/edit#)

It looks like the focus is on what you want.

Monday, March 30 – Friday April 3
Progress:
Converted much of the existing router code to TypeScript, refactored as needed
Wrote directives for Angular 2
Most (35/40) tests passing
Work on documentation system for splitting routing docs into parts for Angular 1 and Angular 2
Goals:
Finish directives for Angular 2

**Comment by hannahhoward** [comment]
Thanks @btford for taking the time to respond to this and I do apologize for pulling you away from coding. The update to the progress document makes a huge difference in terms of clarity of what's happening -- hopefully that's automated as well now so that it doesn't take a lot of time away as well. One other thing that would be super helpful is identifying GH issues are can easily be completed by outside contributors and marking them as such. In a project this early on-- that's also very integrated with two other large codebases-- it's clear some tickets are better left alone to those who have big picture understanding on both the NG1 and NG2 code. I went ahead and implemented support for using directives in 1.x, mainly cause it's one I wanted most, but in retrospect that might have been too many unknowns in terms of the direction you guys for me to implement that properly. If there are tickets that are more chore like -- and that don't require a deep knowledge of the internal process -- I'd love to help out and I imagine others would as well. :)
