### ISSUE TITLE
Link to sibling child route doesn't work if target sibling controller hasn't been instantiated yet

### ISSUE THREAD

**Issue by gsans** [angular/router#248]
There are two root routes: /home and /users. For the users component we define /users/:id. All works as expected with links within the users component.

If I try to add a link from home to /users/:id it wont work tough. But if we try to navigate to users and instantiate the users controller then if we try again the links (on home) will work as expected. Not sure if I am missing something or is an actual bug.

See issue here http://embed.plnkr.co/N4OqwUEFFf1f54g3GQPh/preview

**Comment by mhevery** [comment]
@btford is this the right repo for this?

**Comment by robertdp** [comment]
@gsans Nothing inside UsersController will be run until the controller needs to be instantiated. Using $router.config() only really works for AppController, since that should be instantiated every time, and even then it will only load route configuration for the other controllers that are re.

Try `UsersController.$routeConfig = [];`, which should add the routes when

**Comment by gsans** [comment]
Cool. That fixed the issue.
