### ISSUE TITLE
Angular 1.4rc + router+ material design not working correctly!

### ISSUE THREAD

**Issue by gotenxds** [angular/router#269]
Hi, found an "AMAZING" bug when combining the 3

router seems to create new viewports instead of updating the current one!

plunker: http://plnkr.co/edit/aoYFty2y4MnwxAZZaBfk?p=preview

Seems like this work if we revert to angular 1.4 beta 6

**Comment by shanonvl** [comment]
If you look at the console, there are errors... I noticed that you're including angular-aria and angular-animate `1.3.15` -- you should upgrade these to match the `1.4.rc.0` and it will work:

http://plnkr.co/edit/dbBPHx0J8NXNEGgbQJhv

**Comment by btford** [comment]
I also see what @shanonvl sees. Closing.

**Comment by dmackerman** [comment]
This seems to be happening for me with `ui-router` as well, using RC2. I made sure all my dependencies were correct. We're also using the Material library, at version 0.9. Seeing a ton of errors around ngAnimate - so not sure this is fixed just yet.

**Comment by heidi-de** [comment]
I made an in-house demo 2 days ago with new router 0.5.3, angular 1.4.0-rc.1 and angular-material 0.9.0 and had the same issues, but this was due to a funky bower config which had indeed loaded the 1.3 version of angular animate. Once I switched to the 1.4.0-rc.1 version of angular-animate I didn´t see any further errors. Can you post a plnkr demonstrating the issue?

**Comment by dmackerman** [comment]
@heidi-de: does it work with RC2?

**Comment by heidi-de** [comment]
sorry, I have no idea about ui-router. Do you still get the errors without any router loaded?
