### ISSUE TITLE
Is this repository still in progress?

### ISSUE THREAD

**Issue by alanpurple** [angular/router#374]
I'm curious.

Since angular 1.5.0-beta.0 came out, I just wonder when can I use the actual version of new router for actual beta angular

Is this router will replace old angular-route in 1.5.0 also, right?

**Comment by PascalPrecht** [comment]
@alanpurple as the readme states, this repository is on hold since a couple of months, since the development of the component router has been moved to the angular projects itself for easier setup.

You can take a look at the current state right here: https://github.com/angular/angular/tree/master/modules/angular1_router
