### ISSUE TITLE
docs(*): index pages

### ISSUE THREAD

**Issue by btford** [angular/router#54]
@petebacondarwin – I'm wondering what the best way to create an index page listing the various parts of the documentation with dgeni. I peeked at the configs for angular and your example project a bit, but it wasn't entirely clear to me.

Any advice?

**Comment by petebacondarwin** [comment]
I'll send something over tomorrow

**Comment by btford** [comment]
Thanks!

**Comment by petebacondarwin** [comment]
So what you need is a processor that will add a new doc to the `docs` collection. This doc should have a property that holds a collection of references to all the docs that you want to show on the index page. It should also have an id and path, so that it can be rendered and written. Then you just need to provide a template that will render the collection of references as you see fit.  I will knock up a basic PR for you.

**Comment by petebacondarwin** [comment]
By the way, your usage of markdown is breaking the dgeni generation, since `scripts/markdown.js` is updating the shared `markdown` library to use the async pygmentize highlighter. But the dgeni configuration is expecting to run `markdown` synchronously, so it is not passing a callback.

Do you actually need a markdown task in Gulp? Can this not be handled by dgeni? If it is needed then we need to think of a way of isolating the two uses of markdown from each other.

**Comment by petebacondarwin** [comment]
There you go.

Regarding the markdown stuff. We can easily use dgeni to convert the `*.md` in the project to HTML and put them in the `dist/docs` folder. Moreover, we can then, also automatically include links to them in the index page.  I can create a PR for this too if you like.
